/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package com.pss.dadosclima.view;

import com.pss.dadosclima.presenter.Panels.Painel;
import com.pss.service.LogService;
import enums.TipoLog;
import javax.swing.JDesktopPane;
import javax.swing.JLabel;
import javax.swing.JMenuItem;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author UFES
 */
public class PrincipalView extends javax.swing.JFrame {
    
    private ArrayList<Painel> paineis = new ArrayList<>();
    private int numregistros = 0;
    private LogService log;

    /**
     * Creates new form PrincipalView
     */
    public PrincipalView(LogService log) {
        this.log=log;
        initComponents();
        setExtendedState(java.awt.Frame.MAXIMIZED_BOTH);
        setVisible(true);
        
    }

    public JMenuItem getConfigurarItem() {
        return ConfigurarItem;
    }

    public JLabel getQuantidadeLabel() {
        return quantidadeLabel;
    }

    public JDesktopPane getDesktopPane() {
        return desktopPane;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        JLabel = new javax.swing.JLabel();
        quantidadeLabel = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        ConfigurarItem = new javax.swing.JMenuItem();
        sairItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Estação Climática");
        setForeground(java.awt.Color.gray);

        desktopPane.setBackground(java.awt.Color.lightGray);
        desktopPane.setDoubleBuffered(true);

        JLabel.setText("Quantidade de Registros:");

        quantidadeLabel.setText("0");

        fileMenu.setMnemonic('f');
        fileMenu.setText("File");

        ConfigurarItem.setMnemonic('o');
        ConfigurarItem.setText("Configurar...");
        ConfigurarItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfigurarItemActionPerformed(evt);
            }
        });
        fileMenu.add(ConfigurarItem);

        sairItem.setMnemonic('x');
        sairItem.setText("Sair");
        sairItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairItemActionPerformed(evt);
            }
        });
        fileMenu.add(sairItem);

        menuBar.add(fileMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 935, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JLabel)
                .addGap(3, 3, 3)
                .addComponent(quantidadeLabel)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 612, Short.MAX_VALUE)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLabel)
                    .addComponent(quantidadeLabel)))
        );

        desktopPane.getAccessibleContext().setAccessibleName("Estação Climática");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sairItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_sairItemActionPerformed

    private void ConfigurarItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfigurarItemActionPerformed
        
        Object[] opcoes= TipoLog.values();
        int formato= JOptionPane.showOptionDialog(this, "Formato do log (JSON por padrão)", "Configurações", JOptionPane.DEFAULT_OPTION,JOptionPane.QUESTION_MESSAGE,null,opcoes,opcoes[0]);
        
        if (formato>=0 && formato <opcoes.length){
            if(log.getFormatoLog()!=opcoes[formato]){
                try{
                        switch(formato){
                        case 0:
                           log.setFormatoLog(TipoLog.JSON);
                        break;

                        case 1:
                        log.setFormatoLog(TipoLog.XML);
                        break;
                    }
            }
                catch(Exception e){
                   JOptionPane.showMessageDialog(this,"Erro LogService", "Desculpe", JOptionPane.ERROR_MESSAGE);
                   e.printStackTrace();
               }
             JOptionPane.showMessageDialog(this, "Log será gravado em "+opcoes[formato].toString());   
            }
        }
    }//GEN-LAST:event_ConfigurarItemActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ConfigurarItem;
    private javax.swing.JLabel JLabel;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JLabel quantidadeLabel;
    private javax.swing.JMenuItem sairItem;
    // End of variables declaration//GEN-END:variables

}
